// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejltrhkhsvdtpxkhbher.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqbHRyaGtoc3ZkdHB4a2hiaGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MzMwNjQsImV4cCI6MjA1MjMwOTA2NH0.r7kn9Y1iDPm4KPVxTrH_30akZjjIEgiAkl2UTVtR3MI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);